global:
  path_to_cache:
  combined_npz: true
  imagenet_root:
  debug: 1
  exp_factor: 8
  input_shape: 768
  batch_size: 32
  nb_epochs: 30
  standardize: true
  divide_norm: false
  target_class: ALL
  use_class_tokens: false
  loss_criterion: L1
  lr: 0.0003
  final_lr: 1.0e-06
  run_name: ${model_1}_${model_2}_${model_3}_ex${exp_factor}_bs${batch_size}_topk${top_k}_LR${lr}_class-${target_class}_cross_${loss_criterion}_${nb_epochs}epochs
viz:
  dataset: imagenet
  batch_size: 100
  class_name:  ALL #cottontail rabbit
  sample_size: 5000
  set: val
sae_params:
  encoder_module: mlp_bn_1
  dictionary_initializer: null
  data_initializer: null
  dictionary_normalization: l2
  top_k: 32
model_zoo:
  SigLIP:
    checkpoint_path: checkpoints/uni_SigLIP_checkpoint_29.pth
    input_shape: 768
    num_tokens: 196
    og_model: SigLIP
    model_mean: -0.030537348240613937
    model_std: 2.231515407562256
  DinoV2:
    checkpoint_path: checkpoints/uni_DinoV2_checkpoint_29.pth
    input_shape: 384
    num_tokens: 196
    og_model: DinoV2
    model_mean: 0.03290482237935066
    model_std: 2.474064350128174
  ViT:
    checkpoint_path: checkpoints/uni_ViT_checkpoint_29.pth
    input_shape: 768
    num_tokens: 196
    og_model: ViT
    model_mean: -0.028632672503590584
    model_std: 2.1376500129699707
